// Glossaire Viticolor — termes de dégustation, viticulture et vinification
window.VITICOLOR_GLOSSAIRE = [
["Acescence","Défaut : piqûre acétique donnant des notes de vinaigre ou de vernis (acidité volatile excessive)."],
["Acidité","Colonne vertébrale du vin ; apporte fraîcheur, nervosité et potentiel de garde."],
["Aération","Mise en contact du vin avec l'oxygène (carafage) pour ouvrir les arômes."],
["Ampélographie","Science de l'identification et de la description des cépages."],
["Ample","Vin qui emplit toute la bouche, large et enveloppant."],
["Animal","Famille d'arômes tertiaires : cuir, fourrure, gibier, venaison."],
["AOC","Appellation d'Origine Contrôlée : terroir délimité, cépages, rendements et pratiques encadrés."],
["Apogée","Période où le vin atteint son sommet qualitatif de maturité."],
["Âpre","Sensation rugueuse et desséchante due à des tanins agressifs."],
["Aromatique (cépage)","Cépage dont les arômes variétaux dominent (muscat, gewurztraminer, sauvignon)."],
["Arômes primaires","Arômes issus du raisin lui-même : fruits, fleurs, végétal."],
["Arômes secondaires","Arômes nés de la fermentation : levures, brioche, banane, beurre."],
["Arômes tertiaires","Bouquet développé à l'élevage et au vieillissement : sous-bois, cuir, truffe, fruits secs."],
["Assemblage","Mariage de plusieurs cépages, parcelles ou cuvées pour composer le vin final."],
["Astringence","Sensation d'assèchement du palais provoquée par les tanins."],
["Attaque","Première impression du vin en bouche."],
["Ban des vendanges","Date officielle d'ouverture de la récolte dans une appellation."],
["Barrique","Fût de chêne bordelais de 225 litres."],
["Bâtonnage","Remise en suspension des lies fines dans le fût pour nourrir le vin."],
["Baumé","Ancienne échelle mesurant la richesse en sucre du moût."],
["Biodynamie","Viticulture fondée sur les cycles lunaires et des préparations naturelles (certif. Demeter)."],
["Blanc de blancs","Effervescent issu exclusivement de raisins blancs (chardonnay en Champagne)."],
["Blanc de noirs","Blanc effervescent issu de raisins noirs à jus blanc (pinot noir, meunier)."],
["Boisé","Notes de vanille, toast, fumé ou coco apportées par l'élevage sous bois ; réussi lorsqu'il se fond au fruit."],
["Botrytis","Pourriture noble (Botrytis cinerea) qui concentre sucres et arômes des grands liquoreux."],
["Bouche","Ensemble des sensations gustatives et tactiles : attaque, milieu, finale."],
["Bouchonné","Défaut de goût de liège moisi dû au TCA."],
["Bouquet","Ensemble des arômes d'un vin évolué."],
["Bourbes","Particules solides éliminées du moût blanc avant fermentation (débourbage)."],
["Brett","Brettanomyces : levure de contamination donnant cuir, écurie, sueur de cheval."],
["Brut","Effervescent peu dosé : moins de 12 g/l de sucre."],
["Brut nature","Effervescent sans aucun dosage (moins de 3 g/l)."],
["Capiteux","Vin riche en alcool, presque entêtant."],
["Carafage","Transvasement du vin en carafe pour l'aérer (jeune) ou le séparer de son dépôt (vieux)."],
["Cep","Pied de vigne."],
["Cépage","Variété de vigne cultivée (pinot noir, chardonnay, syrah…)."],
["Chai","Bâtiment où l'on vinifie et élève le vin."],
["Chaptalisation","Ajout de sucre au moût pour augmenter le degré d'alcool (encadré par la loi)."],
["Charnu","Vin qui a de la chair, de la matière fruitée en bouche."],
["Charpenté","Vin de forte constitution tannique, bâti pour la garde."],
["Clavelin","Bouteille de 62 cl réservée au vin jaune du Jura."],
["Climat","En Bourgogne, parcelle de vigne délimitée et nommée depuis des siècles (UNESCO 2015)."],
["Clone","Descendance d'un cep unique sélectionné pour ses qualités."],
["Clos","Parcelle historiquement close de murs (Clos de Vougeot…)."],
["Collage","Clarification du vin par ajout d'une protéine qui entraîne les particules."],
["Complexité","Richesse et diversité des arômes et saveurs ; marque des grands vins."],
["Concentration","Densité de matière (fruit, extrait sec) en bouche."],
["Corsé","Vin puissant, riche en alcool et en matière."],
["Coulure","Accident de floraison : les fleurs non fécondées tombent, réduisant la récolte."],
["Court","Vin dont les arômes disparaissent vite après la déglutition."],
["Crémant","Effervescent de méthode traditionnelle hors Champagne (Alsace, Loire, Bourgogne…)."],
["Cru","Terroir ou domaine reconnu pour sa qualité ; hiérarchisé dans plusieurs régions."],
["Cuvaison","Durée de macération du jus avec les parties solides du raisin."],
["Cuvée","Vin issu d'une sélection particulière (cuve, parcelle, assemblage)."],
["Débourbage","Clarification du moût blanc avant fermentation."],
["Débourrement","Éclosion des bourgeons de la vigne au printemps."],
["Décuvage","Séparation du vin de goutte et du marc après cuvaison."],
["Dégorgement","Expulsion du dépôt de levures d'une bouteille d'effervescent après remuage."],
["Demi-sec","Vin légèrement sucré (effervescents : 32–50 g/l ; tranquilles : 4–12 g/l ou plus selon AOC)."],
["Dépôt","Particules solides (tanins, pigments, tartre) au fond des vieilles bouteilles."],
["Dosage","Liqueur d'expédition ajoutée après dégorgement, déterminant le style (brut, sec, demi-sec)."],
["Douelle","Planche de chêne composant le fût."],
["Éclaircissage","Suppression de grappes en été pour concentrer la récolte (vendanges vertes)."],
["Effeuillage","Suppression de feuilles autour des grappes pour l'ensoleillement et l'aération."],
["Égrappage","Séparation des baies de la rafle avant vinification."],
["Élevage","Période de maturation du vin entre fermentation et mise en bouteille — cuve, fût, foudre, amphore ; il affine tanins et arômes."],
["Empyreumatique","Famille d'arômes de feu : fumé, grillé, café, cacao, goudron."],
["Enherbement","Couvert végétal entre les rangs pour la vie des sols et la concurrence hydrique."],
["Équilibre","Harmonie entre acidité, alcool, tanins et sucres — le critère cardinal."],
["Éraflage","Synonyme d'égrappage."],
["Extraction","Diffusion des tanins et pigments pendant la macération (pigeage, remontage)."],
["Fermentation alcoolique","Transformation des sucres en alcool et CO₂ par les levures ; naissance du vin."],
["Fermentation malolactique","Transformation de l'acide malique (vert, pomme) en acide lactique (souple, beurré) par des bactéries — la « malo », quasi systématique sur les rouges."],
["Filtration","Clarification finale du vin avant mise en bouteille."],
["Finale","Dernière impression en bouche ; sa longueur signe la qualité."],
["Floraison","Fleur de vigne en juin ; elle détermine la date des vendanges (± 100 jours)."],
["Foudre","Grand fût de bois de 20 à 300 hl, marquage boisé discret."],
["Fruité","Dominante d'arômes de fruits frais, mûrs, confits ou secs selon l'évolution."],
["Fût","Tonneau de chêne pour l'élevage (barrique 225 l, pièce 228 l)."],
["Garde (vin de)","Vin construit pour se bonifier plusieurs années en cave."],
["Gelée de printemps","Gel des jeunes pousses en avril-mai, fléau des vignerons."],
["Générique","Appellation régionale de base (Bourgogne, Bordeaux) sans mention de village."],
["Glycérol","Composé onctueux issu de la fermentation, contribue au gras du vin."],
["Gouleyant","Vin souple et léger qui se boit facilement."],
["Goutte (vin de)","Vin qui s'écoule librement au décuvage, avant pressurage du marc."],
["Gras","Texture onctueuse, ronde et enveloppante en bouche."],
["Gravelle","Cristaux de tartre inoffensifs au fond des bouteilles."],
["Greffage","Union d'un cépage européen sur un porte-greffe américain résistant au phylloxéra."],
["Grand cru","Sommet des hiérarchies bourguignonne, champenoise et alsacienne."],
["Herbacé","Notes végétales (herbe coupée, poivron) souvent liées à une maturité incomplète."],
["HVE","Haute Valeur Environnementale : certification agro-environnementale des exploitations."],
["Hybride","Croisement entre vigne européenne et américaine ; base des nouveaux cépages résistants."],
["INAO","Institut national de l'origine et de la qualité, gardien des AOC."],
["Jéroboam","Grand flacon de 3 litres (5 l à Bordeaux)."],
["Larmes","Traînées sur les parois du verre, indice de richesse en alcool et glycérol."],
["Levures","Micro-organismes de la fermentation ; indigènes (du terroir) ou sélectionnées."],
["Levures indigènes","Levures naturellement présentes sur le raisin et au chai, revendiquées par les vignerons nature."],
["Lies","Dépôt de levures mortes après fermentation ; l'élevage « sur lies » nourrit le vin."],
["Liquoreux","Vin riche en sucres résiduels (Sauternes, Jurançon VT) issu de raisins sur-mûris ou botrytisés."],
["Longueur","Persistance aromatique après la déglutition, mesurée en caudalies."],
["Macération","Contact du jus avec peaux et pépins : couleur, tanins, arômes."],
["Macération carbonique","Vinification en grappes entières sous CO₂ (Beaujolais) : fruit éclatant, tanins doux."],
["Madérisé","Vin oxydé rappelant le madère ; défaut sur un vin sec non muté."],
["Magnum","Bouteille de 1,5 litre, format idéal de garde."],
["Marc","Résidu solide du pressurage ; distillé en eau-de-vie."],
["Méthode traditionnelle","Seconde fermentation en bouteille créant l'effervescence (Champagne, crémants)."],
["Millésime","Année de récolte des raisins."],
["Minéral","Descripteur d'arômes et de sensations évoquant la pierre : silex, craie, iode, pierre à fusil — souvent lié à l'acidité et au terroir."],
["Mistelle","Moût muté à l'alcool avant fermentation (Pineau des Charentes, Floc)."],
["Moelleux","Vin doux entre 12 et 45 g/l de sucres résiduels."],
["Monopole","Climat ou clos appartenant à un seul propriétaire (La Tâche, Clos de Tart)."],
["Mutage","Arrêt de la fermentation par ajout d'alcool, conservant les sucres (VDN : Banyuls, Maury)."],
["Nature (vin)","Vin sans intrant ni sulfites ajoutés (ou très peu), de raisins bio récoltés à la main."],
["Négociant","Acheteur de raisins, moûts ou vins qu'il élève et commercialise."],
["Nerveux","Vin dominé par une acidité vive et tonique."],
["Nez","Ensemble des arômes perçus à l'olfaction ; premier nez (verre immobile), deuxième nez (après agitation)."],
["Nouaison","Formation des baies après la floraison."],
["Oxydatif (élevage)","Élevage volontairement au contact de l'air (vin jaune, VDN) : noix, curry, rancio."],
["Ouillage","Remplissage régulier des fûts pour compenser l'évaporation et éviter l'oxydation."],
["Part des anges","Fraction du vin évaporée pendant l'élevage sous bois."],
["Passerillage","Sur-maturation des raisins par dessèchement au soleil ou sur claies."],
["Perlant","Vin tranquille présentant une très légère effervescence."],
["Phénolique (maturité)","Maturité des tanins et pigments, distincte de la maturité en sucre."],
["Phylloxéra","Puceron américain qui détruisit le vignoble européen (1863-1900) ; vaincu par le greffage."],
["Pièce","Fût bourguignon de 228 litres."],
["Pierre à fusil","Note minérale fumée de silex frotté (sauvignon de Pouilly, chablis)."],
["Pigeage","Enfoncement du chapeau de marc dans le jus pour extraire en douceur."],
["Porte-greffe","Racine américaine résistante au phylloxéra sur laquelle on greffe le cépage."],
["Pourriture grise","Botrytis néfaste par temps humide, ennemi de la vendange saine."],
["Premier cru","Second niveau des hiérarchies bourguignonne et champenoise ; mention de climat en Bourgogne."],
["Pressurage","Extraction du jus par pression des raisins ou du marc."],
["Prise de mousse","Seconde fermentation en bouteille qui crée les bulles."],
["Rafle","Partie ligneuse de la grappe ; sa présence apporte structure et fraîcheur (vinification en grappes entières)."],
["Rancio","Arôme oxydatif noble (noix, fruits secs) des VDN élevés longuement."],
["Réduction","État aromatique fermé (allumette, œuf) par manque d'oxygène ; s'ouvre au carafage."],
["Remontage","Pompage du jus par-dessus le chapeau de marc pour l'extraction."],
["Remuage","Rotation progressive des bouteilles pour amener le dépôt vers le goulot (effervescents)."],
["Rendement","Production autorisée par hectare (hl/ha) ; sa maîtrise conditionne la concentration."],
["Rétro-olfaction","Perception des arômes par voie interne en bouche."],
["Robe","Aspect visuel du vin : couleur, intensité, limpidité, reflets."],
["Rognage","Taille des rameaux en été pour maîtriser la vigueur."],
["Rond","Vin souple, sans aspérité tannique ni acidité saillante."],
["Sec","Vin sans sucre résiduel perceptible (moins de 4 g/l)."],
["Second vin","Cuvée issue des lots non retenus pour le grand vin d'un château."],
["Sélection massale","Replantation à partir des meilleurs ceps du domaine, contre le clonage unique."],
["Solera","Élevage par soutirages fractionnés entre fûts d'âges différents (VDN, Jura hors AOC)."],
["Sommelier","Professionnel du service et du conseil du vin en restauration."],
["Soutirage","Transvasement du vin pour le séparer de ses lies."],
["Soyeux","Texture tannique fine et caressante (grands pinots)."],
["Structure","Architecture du vin : acidité + tanins + alcool + matière."],
["Sucres résiduels","Sucres non fermentés restant dans le vin fini."],
["Sulfites","SO₂ protecteur contre l'oxydation et les bactéries ; dosé, il est mentionné dès 10 mg/l."],
["Sur lattes","Bouteilles de champagne en cours de prise de mousse, couchées en cave."],
["Sur lie","Élevage au contact des lies fines sans soutirage (Muscadet)."],
["Tanins","Composés phénoliques des peaux, pépins et rafles ; ils structurent les rouges, assèchent le palais jeunes, se fondent avec l'âge."],
["Tastevin","Coupelle d'argent traditionnelle de dégustation bourguignonne."],
["TCA","Trichloroanisole, molécule du goût de bouchon."],
["Terroir","Alliance unique d'un sol, d'un climat, d'une exposition et d'un savoir-faire humain — le concept fondateur des AOC françaises."],
["Tirage","Mise en bouteille avec liqueur de tirage pour la prise de mousse."],
["Tranquille (vin)","Vin non effervescent."],
["Tries","Passages successifs de vendange pour ne cueillir que les raisins botrytisés (liquoreux)."],
["Tuffeau","Craie du Val de Loire, sol et caves troglodytes de Vouvray et Saumur."],
["Typicité","Caractère fidèle au cépage, au terroir et à l'appellation."],
["Vendanges tardives","Récolte sur-mûrie donnant des vins moelleux (Alsace, Jurançon)."],
["Vendange verte","Éclaircissage estival des grappes excédentaires."],
["Véraison","Changement de couleur des baies en août, début de la maturation."],
["Vigneron","Celui qui cultive la vigne et fait le vin — de la taille à la mise."],
["Vin de garde","Vin dont la structure permet un long vieillissement bénéfique."],
["Vin de goutte","Vin écoulé sans pressurage, le plus fin."],
["Vin de presse","Vin issu du pressurage du marc, plus tannique."],
["Vin de voile","Vin élevé sous un voile de levures sans ouillage (vin jaune, Gaillac)."],
["Vin doux naturel","Vin muté à l'alcool en cours de fermentation (Banyuls, Maury, Rivesaltes, muscats)."],
["Vin jaune","Savagnin jurassien élevé 6 ans et 3 mois sous voile, en clavelin."],
["Vin muté","Vin dont la fermentation est arrêtée par ajout d'alcool."],
["Vinification","Ensemble des opérations transformant le raisin en vin."],
["Vin orange","Blanc vinifié comme un rouge, avec macération des peaux."],
["Vivace","Acidité fraîche et saillante, signe de jeunesse."],
["Volatile (acidité)","Acides volatils (acétique) ; à faible dose complexité, à forte dose défaut."]
];
